export const team = [
  {
    team: 'Management',
    name: 'Faizy Ahmed',
    role: 'Co-Founder',
    imageUrl: '/imgs/Faizy Ahmed.jpg',
  },
  {
    team: 'Management',
    name: 'Muhamed Ashhar',
    role: 'Co-Founder',
    imageUrl: '/imgs/Muhamed Ashhar.jpg',
  },
  {
    team: 'Management',
    name: 'Sumiko Jividen',
    role: 'COO',
    imageUrl: '/imgs/Sumiko Jividen.jpg',
  },
  {
    team: 'Management',
    name: 'Ben X Trinh',
    role: 'CSO',
    imageUrl: '/imgs/Ben X. Trinh.jpg',
  },
  {
    team: 'Management',
    name: 'Dr. Keith Barrows',
    role: 'CLO',
    imageUrl: '/imgs/Dr Keith Barrows.jpg',
  },
  {
    team: 'Directors',
    name: 'Marce Moya Ochoa',
    role: 'Art Director',
    imageUrl: '/imgs/Marce Moya Ochoa.jpg',
  },
  {
    team: 'Directors',
    name: 'David Salisbury',
    role: 'Creative Director',
    imageUrl: '/imgs/David Salisbury.jpg',
  },
  {
    team: 'Directors',
    name: 'Andrew Klein',
    role: 'Marketing Director',
    imageUrl: '/imgs/Andrew Klein.jpg',
  },
  {
    team: 'Directors',
    name: 'Nikhil Malankar',
    role: 'Lead Game Developer',
    imageUrl: '/imgs/Nikhil Malankar.jpg',
  },
  {
    team: 'Developers',
    name: 'Joseph Ashwin',
    role: 'Smart Contract Developer',
    imageUrl: '/imgs/Joseph Ashwin.jpg',
  },
  {
    team: 'Developers',
    name: 'Akhil P. Raj',
    role: 'Blockchain Developer',
    imageUrl: '/imgs/Akhil P Raj.jpg',
  },
  {
    team: 'Developers',
    name: 'Ahmed Farrag',
    role: 'Lead Game Developer',
    imageUrl: '/imgs/Ahmed Farrag.jpg',
  },
  {
    team: 'Developers',
    name: 'Sudarshan Thube',
    role: 'Game Developer',
    imageUrl: '/imgs/Sudarshan Thube.jpg',
  },
  {
    team: 'Developers',
    name: 'Pankaj P K',
    role: 'Full Stack Developer',
    imageUrl: '/imgs/Pankaj Pk.jpg',
  },
  {
    team: 'Developers',
    name: 'Taron Harutyunyan',
    role: 'Game Developer',
    imageUrl: '/imgs/Taron Harutyunyan.jpg',
  },
  {
    team: 'Developers',
    name: 'Ihor Nikolaiev',
    role: 'Game Designer',
    imageUrl: '/imgs/Ihor Nikolaiev.jpg',
  },
  {
    team: 'Marketing',
    name: 'Rishi Krishna',
    role: 'Marketing Manager',
    imageUrl: '/imgs/Rishi Krishna.jpg',
  },
  {
    team: 'Marketing',
    name: 'Hafis Riyam',
    role: 'Community/Recruitment Manager',
    imageUrl: '/imgs/Hafis Riyam.jpg',
  },
  {
    team: 'Marketing',
    name: 'Prem Sagar',
    role: 'Business Development',
    imageUrl: '/imgs/Prem Sagar.jpg',
  },
  {
    team: 'Marketing',
    name: 'Mathew Rajan',
    role: 'Marketing Executive',
    imageUrl: '/imgs/Mathew Rajan.jpg',
  },
  {
    team: 'Marketing',
    name: 'Akshay Kumar',
    role: 'Social Media Manager',
    imageUrl: '/imgs/Akshay Kumar.jpg',
  },
  {
    team: 'Marketing',
    name: 'Mohammed Saayed Navas',
    role: 'Marketing Executive',
    imageUrl: '/imgs/Mohammed Saayed Navas.jpg',
  },
  {
    team: 'Marketing',
    name: 'Jade',
    role: 'Business Operations Associate',
    imageUrl: '/imgs/Jade.jpg',
  },
  {
    team: 'Artists',
    name: 'Milovan Eric',
    role: 'Product Designer',
    imageUrl: '/imgs/Milovan Erić.jpg',
  },
  {
    team: 'Artists',
    name: 'Janet Mach',
    role: 'UX/UI Designer',
    imageUrl: '/imgs/Janet Mach.jpg',
  },
  {
    team: 'Artists',
    name: 'Tanwir Mohammed',
    role: '2D Illustrator',
    imageUrl: '/imgs/TANWIR MOHAMMED.jpg',
  },
  {
    team: 'Artists',
    name: 'Nilansh Sharma',
    role: 'Grooming Artist',
    imageUrl: '/imgs/Nilansh sharma.jpg',
  },
  {
    team: 'Artists',
    name: 'Ravi Sharma',
    role: '3D Animator',
    imageUrl: '/imgs/Ravi Sharma.jpg',
  },
  {
    team: 'Artists',
    name: 'Ritam Chatterjee',
    role: 'Texturing & Look-Dev Artist',
    imageUrl: '/imgs/Ritam Chatterjee.jpg',
  },
  {
    team: 'Artists',
    name: 'Atanu De',
    role: '3D Modelling, Texture and Look-Dev Artist',
    imageUrl: '/imgs/Atanu De.jpg',
  },
  {
    team: 'Artists',
    name: 'Temitope Falade',
    role: '3D Animation & Rigging Artist',
    imageUrl: '/imgs/Temitope FALADE.jpg',
  },
  {
    team: 'Artists',
    name: 'Souvik Mondal',
    role: '3D Modelling Artist',
    imageUrl: '/imgs/Souvik Mondal.jpg',
  },
  {
    team: 'Artists',
    name: 'Pavan Kumar',
    role: '3D Artist',
    imageUrl: '/imgs/Pavan kumar.jpg',
  },
  {
    team: 'Artists',
    name: 'Sérgio Sampaio',
    role: 'Motion Designer',
    imageUrl: '/imgs/Sérgio Sampaio.jpg',
  },
  {
    team: 'Artists',
    name: 'Teuku Dhani Yanzah',
    role: 'Graphic Designer',
    imageUrl: '/imgs/Teuku Yanzah.jpg',
  },
  {
    team: 'Artists',
    name: 'Pradeep Kumar',
    role: 'FX Artist',
    imageUrl: '/imgs/Pradeep Kumar.jpg',
  },
  {
    team: 'Artists',
    name: 'Shruti Guneta',
    role: 'FX Artist',
    imageUrl: '/imgs/Shruti Guneta.jpg',
  },
  {
    team: 'Writers',
    name: 'Pragya Pallavi',
    role: 'Storyboard/Content Writer',
    imageUrl: '/imgs/Pragya Pallavi.jpg',
  },
  {
    team: 'Writers',
    name: 'Tom Baldwin',
    role: 'Writer',
    imageUrl: '/imgs/Tom Baldwin.jpg',
  },
  {
    team: 'Writers',
    name: 'Murray Blehart',
    role: 'Writer',
    imageUrl: '/imgs/Murray (MJ) Blehart.jpg',
  },
  {
    team: 'Advisors',
    name: 'Edouard Faure Cooper',
    role: 'Web3 Startup Advisor to: Portal Finance, Affy, Investdex.io, Zam & KOL for Sidus, Netvrk, Lunaverse.',
    imageUrl: '/imgs/.jpg',
  },
  {
    team: 'Advisors',
    name: 'Saiprasad Raut',
    role: 'Co-Chair Technical & Product. Committee of Hedera.',
    imageUrl: '/imgs/.jpg',
  },
  {
    team: 'Advisors',
    name: 'Nova Lorraine',
    role: 'TedX Speaker 22 Creative Director of Raine Magazine Advisor of MetaGameHub DAO.',
    imageUrl: '/imgs/.jpg',
  },
  {
    team: 'Advisors',
    name: 'Akash Agrawa',
    role: 'Growth Strategist & Brand Builder, Ex Sony, Nike, Walmart NFT Metaverse Web3 Consultant Angel Investor',
    imageUrl: '/imgs/.jpg',
  },
];
