export const team = [
    {
        team: "Management",
        name: "Faizy Ahmed",
        role: "Co-Founder",
        imageUrl: "/imgs/Faizy Ahmed.jpg",
        linkedin: "https://www.linkedin.com/in/faizy-ahmed-a35245233",
    },
    {
        team: "Management",
        name: "Muhamed Ashhar",
        role: "Co-Founder",
        imageUrl: "/imgs/Muhamed Ashhar.jpg",
        linkedin: "https://www.linkedin.com/in/muhamed-ashhar/",
    },
    {
        team: "Management",
        name: "Sumiko Jividen",
        role: "COO",
        imageUrl: "/imgs/Sumiko Jividen.jpg",
        linkedin: "https://www.linkedin.com/in/sumiko-jividen-mba-68a3b18b/",
    },
    {
        team: "Management",
        name: "Ben X Trinh",
        role: "CSO",
        imageUrl: "/imgs/Ben X. Trinh.jpg",
        linkedin: "https://www.linkedin.com/in/benxtrinh",
    },
    {
        team: "Management",
        name: "Dr. Keith Barrows",
        role: "CLO",
        imageUrl: "/imgs/Dr Keith Barrows.jpg",
        linkedin: "https://www.linkedin.com/in/keithobarrows/",
    },
    {
        team: "Directors",
        name: "Marce Moya Ochoa",
        role: "Art Director",
        imageUrl: "/imgs/Marce Moya Ochoa.jpg",
        linkedin: "https://www.linkedin.com/in/marcemoyaochoa",
    },
    {
        team: "Directors",
        name: "David Salisbury",
        role: "Creative Director",
        imageUrl: "/imgs/David Salisbury.jpg",
        linkedin: "linkedin.com/in/david-salisbury-32539b1b",
    },
    {
        team: "Directors",
        name: "Andrew Klein",
        role: "Marketing Director",
        imageUrl: "/imgs/Andrew Klein.jpg",
        linkedin: "https://www.linkedin.com/in/andrewkleinonline",
    },
    {
        team: "Directors",
        name: "Nikhil Malankar",
        role: "Lead Game Developer",
        imageUrl: "/imgs/Nikhil Malankar.jpg",
        linkedin: "https://www.linkedin.com/in/nikhilmalankar/",
    },
    {
        team: "Developers",
        name: "Eric Wang",
        role: "Blockchain Developer",
        imageUrl: "/imgs/Eric Wang.jpeg",
        linkedin: "https://www.linkedin.com/in/eric-wang-348306245/",
    },
    {
        team: "Developers",
        name: "Joseph Ashwin",
        role: "Smart Contract Developer",
        imageUrl: "/imgs/Joseph Ashwin.jpg",
        linkedin: "https://www.linkedin.com/in/josephashwin",
    },
    {
        team: "Developers",
        name: "Akhil P. Raj",
        role: "Blockchain Developer",
        imageUrl: "/imgs/Akhil P Raj.jpg",
        linkedin: "https://www.linkedin.com/in/m-akhil-p-raj-692182225",
    },
    {
        team: "Developers",
        name: "Ahmed Farrag",
        role: "Lead Game Developer",
        imageUrl: "/imgs/Ahmed Farrag.jpg",
        linkedin: "https://www.linkedin.com/in/ahmad-farrag",
    },
    {
        team: "Developers",
        name: "Sudarshan Thube",
        role: "Game Developer",
        imageUrl: "/imgs/Sudarshan Thube.jpg",
        linkedin: "https://www.linkedin.com/in/sudarshan-thube-892177117",
    },
    {
        team: "Developers",
        name: "Pankaj P K",
        role: "Full Stack Developer",
        imageUrl: "/imgs/Pankaj Pk.jpg",
        linkedin: "https://www.linkedin.com/in/pankaj-pramanik",
    },
    {
        team: "Developers",
        name: "Taron Harutyunyan",
        role: "Game Developer",
        imageUrl: "/imgs/Taron Harutyunyan.jpg",
        linkedin: "https://www.linkedin.com/in/tharutyunyan",
    },
    {
        team: "Developers",
        name: "Ihor Nikolaiev",
        role: "Game Designer",
        imageUrl: "/imgs/Ihor Nikolaiev.jpg",
        linkedin: "https://www.linkedin.com/in/ihor-nikolaiev-🇺🇦-9aa45ba5/",
    },
    {
        team: "Marketing",
        name: "Rishi Krishna",
        role: "Marketing Manager",
        imageUrl: "/imgs/Rishi Krishna.jpg",
        linkedin: "https://www.linkedin.com/in/rishi-krishna-524063233/",
    },
    {
        team: "Marketing",
        name: "Said Bel",
        role: "Motion Graphics Designer",
        imageUrl: "/imgs/Said Bel.jpeg",
        linkedin: "https://www.linkedin.com/in/mo-said-belaroussi-423b9b1a4",
    },
    {
        team: "Marketing",
        name: "Ahmed Diab",
        role: "3D Graphic Designer",
        imageUrl: "/imgs/Ahmed Diab.jpeg",
        linkedin: "https://www.linkedin.com/in/eljokerthedarkstar",
    },
    {
        team: "Marketing",
        name: "Ren Blaze",
        role: "Recruitment Manager",
        imageUrl: "/imgs/Ren Blaze.jpg",
        linkedin: "https://www.linkedin.com/in",
    },
    {
        team: "Marketing",
        name: "Prem Sagar",
        role: "Business Development Executive",
        imageUrl: "/imgs/Prem Sagar.jpg",
        linkedin: "https://www.linkedin.com/in/prem-sagar-n-2062951b8/",
    },
    {
        team: "Marketing",
        name: "Rajiv Rathod",
        role: "Community Moderator",
        imageUrl: "/imgs/Rajiv rathod.jpeg",
        linkedin: "https://www.linkedin.com/in/rajiv-rathod-crxo/",
    },
    {
        team: "Marketing",
        name: "Mathew Rajan",
        role: "Community Moderator",
        imageUrl: "/imgs/Mathew Rajan.jpg",
        linkedin: "https://www.linkedin.com/in/mathew-rajan",
    },
    {
        team: "Marketing",
        name: "Akshay Kumar",
        role: "Social Media Manager",
        imageUrl: "/imgs/Akshay Kumar.jpg",
        linkedin: "https://www.linkedin.com/in/akshay-kumar-824a00131",
    },
    {
        team: "Marketing",
        name: "Ashni Christenson",
        role: "Influencer Manager",
        imageUrl: "/imgs/Ashni.jpeg",
        linkedin: "https://www.linkedin.com/in/ashley-christenson0319",
    },
    {
        team: "Marketing",
        name: "Charlie Davies",
        role: "Motion Graphics Designer",
        imageUrl: "/imgs/Charles Davies.jpeg",
        linkedin: "https://www.linkedin.com/in/chdavies1",
    },
    {
        team: "Marketing",
        name: "George Sotirov",
        role: "Motion Graphics Designer",
        imageUrl: "/imgs/George sotirov.jpeg",
        linkedin: "https://www.linkedin.com/in/george-sotirov/",
    },
    {
        team: "Marketing",
        name: "Ismael ter Veer",
        role: "Community Manager",
        imageUrl: "/imgs/Ismael ter veer.jpeg",
        linkedin: "https://www.linkedin.com/in/ismaelterveer",
    },
    {
        team: "Marketing",
        name: "Mohammed Saayed Navas",
        role: "Marketing Executive",
        imageUrl: "/imgs/Mohammed Saayed Navas.jpg",
        linkedin: "https://www.linkedin.com/in/mohammed-saayed-navas-331a41233",
    },
    {
        team: "Marketing",
        name: "Pranjal Podder",
        role: "Meme Officer",
        imageUrl: "/imgs/Pranjal podder.jpeg",
        linkedin: "https://www.linkedin.com/in/pranjal-poddar",
    },
    {
        team: "Marketing",
        name: "Jade",
        role: "Head of Community",
        imageUrl: "/imgs/Jade.jpg",
        linkedin: "https://www.linkedin.com/in/jade-nutty-2065a2243",
    },
    {
        team: "Developers",
        name: "Milovan Eric",
        role: "Product Designer",
        imageUrl: "/imgs/MilovanEric.jpg",
        linkedin: "https://www.linkedin.com/in/milovaneric",
    },
    {
        team: "Developers",
        name: "Janet Mach",
        role: "UX/UI Designer",
        imageUrl: "/imgs/Janet Mach.jpg",
        linkedin: "https://www.linkedin.com/in/janetmach",
    },
    {
        team: "Developers",
        name: "Jatin Sharma",
        role: "Unreal Game Developer",
        imageUrl: "/imgs/Jatin Sharma.jpeg",
        linkedin: "https://www.linkedin.com/in/itz-jatin-sharma-097778197",
    },
    {
        team: "Developers",
        name: "Rustu Goker",
        role: "Game Developer",
        imageUrl: "/imgs/Rusty Goker.jpeg",
        linkedin: "linkedin.com/in/rustu-goker-16368523b",
    },
    {
        team: "Marketing",
        name: "Tanwir Mohammed",
        role: "Community Moderator",
        imageUrl: "/imgs/TANWIR MOHAMMED.jpg",
        linkedin: "https://www.linkedin.com/in/tanwir-mohammed-877840198/",
    },
    {
        team: "Marketing",
        name: "Amina Filipović",
        role: "Associate Social Media Manager",
        imageUrl: "/imgs/Amina filipovic.jpeg",
        linkedin: "https://www.linkedin.com/in/amina-filipović-986bb9223",
    },
    {
        team: "Artists",
        name: "Nilansh Sharma",
        role: "Grooming Artist",
        imageUrl: "/imgs/Nilansh sharma.jpg",
        linkedin: "https://www.linkedin.com/in/nilansh-sharma-5202b3180",
    },
    {
        team: "Artists",
        name: "Ravi Sharma",
        role: "3D Animator",
        imageUrl: "/imgs/Ravi Sharma.jpg",
        linkedin: "https://www.linkedin.com/in/ravi-sharma-b2132567/",
    },
    {
        team: "Artists",
        name: "Temitope Falade",
        role: "3D Animation & Rigging Artist",
        imageUrl: "/imgs/Temitope FALADE.jpg",
        linkedin: "https://www.linkedin.com/in/temitope-falade-578107120",
    },
    {
        team: "Artists",
        name: "Pavan Kumar",
        role: "3D Artist",
        imageUrl: "/imgs/Pavan kumar.jpg",
        linkedin: "https://www.linkedin.com/in/pavan-kumar-0666a8130",
    },
    {
        team: "Artists",
        name: "Sérgio Sampaio",
        role: "Motion Designer",
        imageUrl: "/imgs/Sergio Sampaio.jpg",
        linkedin: "https://www.linkedin.com/in/sérgio-sampaio",
    },
    {
        team: "Artists",
        name: "Teuku Dhani Yanzah",
        role: "Graphic Designer",
        imageUrl: "/imgs/Teuku Yanzah.jpg",
        linkedin: "https://linkedin.com/in/teuku-dhani-yanzah-27880a133",
    },
    {
        team: "Artists",
        name: "Vibhu Knanoja",
        role: "3D Character Artist",
        imageUrl: "/imgs/Vibhu knanoja.jpeg",
        linkedin: "https://www.linkedin.com/in/vibhu-kanojia-63a38b191",
    },
    {
        team: "Artists",
        name: "Yesesvee Acharya",
        role: "Concept Artist",
        imageUrl: "/imgs/Yassesvee Acharya.jpg",
        linkedin: "https://www.linkedin.com/in/yesesvee-acharya-868a6320",
    },
    {
        team: "Artists",
        name: "Shruti Guneta",
        role: "VFX Artist",
        imageUrl: "/imgs/Shruti Guneta.jpg",
        linkedin: "https://www.linkedin.com/in/shruti-guneta-09279916b",
    },
    {
        team: "Artists",
        name: "Akash Veppulu",
        role: "Unreal Engine Artist ",
        imageUrl: "/imgs/Akash veppulu.jpeg",
        linkedin: "https://www.linkedin.com/in/akash-veppulu-105816a9",
    },
    {
        team: "Artists",
        name: "José M. Cabello Bàrzanas",
        role: "3D Animator ",
        imageUrl: "/imgs/Jose MCB.jpeg",
        linkedin: "https://www.linkedin.com/in/jbarzanas",
    },
    {
        team: "Artists",
        name: "Kunal Aher",
        role: "3D Artist ",
        imageUrl: "/imgs/Kunal Aher.jpeg",
        linkedin: "https://www.linkedin.com/in/kunal-aher-9b3559202",
    },
    {
        team: "Artists",
        name: "Kishor Chauhan",
        role: "Environment Artist",
        imageUrl: "/imgs/Kishor.jpeg",
        linkedin: "https://www.linkedin.com/in/kishor-chauhan-896251181",
    },
    {
        team: "Artists",
        name: "Mohammed Aquib",
        role: "Art Lead",
        imageUrl: "/imgs/Mohammed Aquib.jpeg",
        linkedin: "https://www.linkedin.com/in/mohammadaquib1",
    },
    {
        team: "Artists",
        name: "Mousam Ghosh",
        role: "3D Character Artist",
        imageUrl: "/imgs/Mousam ghosh.jpg",
        linkedin: "https://www.linkedin.com/in/mousam-ghosh-b9389b155",
    },
    {
        team: "Artists",
        name: "Payal Agarwal",
        role: "Rigging Artist",
        imageUrl: "/imgs/Payal Agarwal.jpeg",
        linkedin: "https://www.linkedin.com/in/payal-agarwal-898758ba",
    },
    {
        team: "Artists",
        name: "Pradeep Kumar",
        role: "VFX Artist ",
        imageUrl: "/imgs/Sai Prasad Raut.jpg",
        linkedin: "https://www.linkedin.com/in/pradeep-kumar-845754197/",
    },
    {
        team: "Artists",
        name: "Sanjib Ganguly",
        role: "Rigging Artist",
        imageUrl: "/imgs/Sanjib Ganguly.jpeg",
        linkedin: "https://www.linkedin.com/in/sanjib-ganguly-29410a25",
    },
    {
        team: "Writers",
        name: "Pragya Pallavi",
        role: "Storyboard Writer",
        imageUrl: "/imgs/Pragya Pallavi.jpg",
        linkedin: "https://www.linkedin.com/in/pragyapallavi/",
    },
    {
        team: "Writers",
        name: "Tom Baldwin",
        role: "Storyboard Writer",
        imageUrl: "/imgs/Tom Baldwin.jpg",
        linkedin: "https://linkedin.com/in/t-n-tom-baldwin-9999a41a7",
    },
    {
        team: "Writers",
        name: "Murray Blehart",
        role: "Storyboard Writer",
        imageUrl: "/imgs/Murray (MJ) Blehart.jpg",
        linkedin: "https://linkedin.com/in/murray-mj-blehart-9859543",
    },
    {
        team: "Writers",
        name: "Uforo-Abasi Essien",
        role: "Content Writer",
        imageUrl: "/imgs/Uforo-Abasi Essien.jpeg",
        linkedin: "https://www.linkedin.com/in/uforo-abasi-essien-a31a811a2",
    },

    {
        team: "Advisors",
        name: "Saiprasad Raut",
        role: "Co-Chair Technical & Product Committe of Hedera ",
        imageUrl: "/imgs/Sai Prasad Raut.jpg",
        linkedin: "https://in.linkedin.com/in/saiprasad-raut-857a154",
    },
    {
        team: "Advisors",
        name: "Nova Lorraine",
        role: "TedX Speaker 22'. Creative Director of Raine Magazine. Advisor of MetaGameHub DAO",
        imageUrl: "/imgs/Nova Lorraine.jpg",
        linkedin: "https://www.linkedin.com/in/novalorraine",
    },
    {
        team: "Advisors",
        name: "Akash Agrawal",
        role: "Ex- Nike, Sony, Wallmart",
        imageUrl: "/imgs/Akash Agrawal.jpg",
        linkedin: "https://www.linkedin.com/in/agrawalakash",
    },
    {
        team: "Advisors",
        name: "James Rothwell",
        role: "VP Global marketing at Binance",
        imageUrl: "/imgs/James Rothwell-B_W.jpeg",
        linkedin: "https://www.linkedin.com/in/james-rothwell-85421430",
    },
];
